# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J6ByGyB29oKwUDN1lyFn-52p83tkZYBl

#Task 2
In this task we have to predict the percentage of marks that a student is expected to score based on number of study hours.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt  
# %matplotlib inline

url = "http://bit.ly/w-data"
s_data = pd.read_csv(url)
print("Data imported successfully")

s_data.head(10)

"""Plotting the distribution of scores"""

s_data.plot(x='Hours', y='Scores', style='o')  
plt.title('Hours vs Percentage')  
plt.xlabel('Hours Studied')  
plt.ylabel('Percentage Score')  
plt.show()

"""Preparing the data"""

X = s_data.iloc[:, :-1].values  
y = s_data.iloc[:, 1].values

from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                            test_size=0.2, random_state=0)

"""Training and Testing of Algorithm"""

from sklearn.linear_model import LinearRegression  
regressor = LinearRegression()  
regressor.fit(X_train, y_train) 

print("Training complete.")

"""Plotting for the test data"""

line = regressor.coef_*X+regressor.intercept_


plt.scatter(X, y)
plt.plot(X, line);
plt.show()

"""Predictions"""

print(X_test) 
y_pred = regressor.predict(X_test)

df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})  
df

p = regressor.predict([[9.25]])
print("Predicted Score = {}".format(p))

"""Final Output"""

print("The Student Studies for 9.25 hours in a day would Probably score{}".format(p))

"""Evaluating Model"""

from sklearn import metrics  
print('MAE:', metrics.mean_absolute_error(y_test, y_pred))